### ISSUE TITLE
Timed BlockIpAddress unbans players who was banned by Ban function

### ISSUE THREAD

**Issue by NexiusTailer** [Open-GTO/sa-mp-fixes#123]
If we use BlockIpAddress for some IP and for some time in ms (more that 0), the player with this IP will be unbanned even despite the fact he was already banned by Ban(playerid) function earlier. And only after the server restart, the player with this IP will be banned again as the server will also reload samp.ban file.

**Comment by NexiusTailer** [comment]
Some important note: it should be checked on a hosted (remote) server, not on localhost (as BlockIpAddress won't work for a local IP).

**Comment by Y-Less** [comment]
If an IP is already banned, why is it being blocked?  They shouldn't be able to connect in the first place.  In which case the obvious solution would be to check the existing bans and do nothing if the IP is listed.

**Comment by NexiusTailer** [comment]
There are no native functions like IsIpAddressBlocked or something similar, so the solution isn't so quick and obvious. The problem was discovered on the following code:
```
public OnPlayerDisconnect(playerid, reason)
{
	if(!IsPlayerNPC(playerid))
	{
		BlockIpAddress(ACInfo[playerid][acIp], 12000); //Simple anti-reconnect
	}
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp("/banme", cmdtext, true)) //Just for test
	{
		Ban(playerid);
		return 1;
	}
	return 0;
}
```

And it has no apparent contradictions. Anti-reconnect by itself looks quite correct without any extra code as well as the usual ban command, which doesn't make you think that it lacks something to work correctly. The fact that the server’s behavior changes so suddenly is unpredictable for the most people who could face it and it’s obvious that such people will not find the cause of the problem so fast when players can somehow play on their servers even after ban. I still think this behavior wasn't planned (and documented) and could have been fixed somewhere in such includes.

**Comment by Y-Less** [comment]
You're right that's probably not intended, but neither is temp banning a permanently banned person.  The real question is what is the correct behaviour?  If you ban someone, then ban them for only 10 minutes, why shouldn't they be able to reconnect after 10 minutes?  Surely the temp ban that came second should take precedence.

You ban someone, decide that's too harsh, and decide to temp ban them instead.  But then the temp ban expires and they don't get unbanned.  That would be more surprising behaviour, rather than that weird misuse of the ban system in your example (there is a "kick" reason given).

**Comment by NexiusTailer** [comment]
The answer for "which behaviour is right" can be probably formed from this state: if a player was banned by Ban function and added to samp.ban (so it is a permanent block), and his IP banned for some limited time after it (temporary block), then after the timed ban is over, samp.ban shouldn't be ignored/desynced and ban should be applied from it as a permanent thing. If you still want to have priority for timed ban as a latest applied action, you again have contradictions with the info in samp.ban - and that is the main problem itself. Another strange thing you'll get is the fact that this player will be banned again after the server restart.

**Comment by Y-Less** [comment]
The other argument is that if you temp ban someone they should be removed from the permanent ban file.  I don't think either version is more right than the other, but I do think the issue here is using the ban system for something it wasn't designed for - an auto reconnect blocker, then complaining that it doesn't work for that.

**Comment by NexiusTailer** [comment]
Anyway, some more frequent 'bans data' updating on the server in accordance with samp.ban would create less problems like that and give more confidence to the user that it hasn't been different for a long time.
