### ISSUE TITLE
BODY_PART_TORSO

### ISSUE THREAD

**Issue by Y-Less** [Open-GTO/sa-mp-fixes#38]
Basically #20 had some interesting discussion, but got closed and seemingly forgotten (at least I forgot about it).  I just found my experiements with the warnings again so thought I should revive the debate.  I personally think there's something in there due to the ambiguities, but what do others think?

**Comment by rt-2** [comment]
As explained in the other thread, I think we should keep the version that has been the most use for the most time by the most people to avoid code break. The thing is how to know that? It is sad that the samp wiki doesn't provide a simple answer. It did, but it can be modified anytime and it did when I opened #20.
rt-2

**Comment by ziggi** [comment]
I vote for _right_ code, even if this code will break something.

**Comment by Y-Less** [comment]
Don't forget that all fixes are optionally compiled, so if it does break something, either fix it or disable it.

**Comment by ziggi** [comment]
Why this issue exists? I don't understand it.
@rt-2 wants to keep wrong fixes code for save compatibility, I want to keep right code because this is right.  I don't see a solution for both sides. So, if you disagree with my opinion - just fork this repo and maintain your version of this include.

I want to close this again, but I will wait for replies.

**Comment by rt-2** [comment]
Yeah and rereading the comment I left here yesterday it seems I edited out the fact that:
I understand the disagreement, all I want is a **steady** answer that wont change again.

At most we can debate this now once and for all since the last change was just like a month ago.
I personally changed my code and uses the supposedly 'right' definitions in this include since the last discussion because I just wanna be standard.

My personal 'vote' on this issue is that we should use the code that has been used for the most time whatever it is.

rt-2

**Comment by Y-Less** [comment]
I reopened it because despite reading that, I still wasn't sure what the popular answer was, nor even if the values used matched the names.

**Comment by IstuntmanI** [comment]
I don't know why there is such a dispute for this easily testable thing:
chest = "```the front surface of a person's or animal's body between the neck and the abdomen```"
torso = "```the trunk of the human body```"
groin = "```the area between the abdomen and the thigh on either side of the body```"

Because there are so many comments related to this thing I made a small test script:
```pawn
#include <a_samp>
#include <zcmd>

new bodyparts[ MAX_PLAYERS ];

CMD:bodyparts( playerid, params[ ] )
{
	if( ( bodyparts[ playerid ] = !bodyparts[ playerid ] ) )
		SendClientMessage( playerid, -1, "ON" );

	else
        	SendClientMessage( playerid, -1, "OFF" );

	return 1;
}

new gsString[ 64 ];

public OnPlayerGiveDamage( playerid, damagedid, Float:amount, weaponid, bodypart )
{
	if( bodyparts[ playerid ] )
	{
		format( gsString, 64, "damagedID: %d | amount: %.2f | weaponid: %d | bodypart: %d", damagedid, amount, weaponid, bodypart );
		SendClientMessage( playerid, -1, gsString );
	}

	return 1;
}
```
I enabled the command and I started shooting a standing test player. He used a male skin and a female (with pants, to be sure) skin.

The ID shown for the torso (not just the chest, but the stomach too, without the groin area) is 3. The perfect groin area was shown as ID 4. Other IDs are perfectly defined in this include. The approximate hitbox I saw:
![hitbox](https://user-images.githubusercontent.com/6208948/27662075-0dc0c058-5c65-11e7-8193-1128d1184454.jpg)

I agree with @ziggi, the right code should be used, so a commit should be made to rename ```BODY_PART_CHEST``` to ```BODY_PART_TORSO``` (well, it is the torso, but without the groin area, so ```BODY_PART_CHEST_AND_STOMACH``` would be correct but way too much).

"Torso" should be just fine for ID 4. Chest is incorrect for sure.

**Comment by Y-Less** [comment]
Best reply yet, thank you!  I should have done the research myself but didn't.  So seriously thank you for so explicitly clarifying everything.

**Comment by rt-2** [comment]
I agree.
So this http://wiki.sa-mp.com/wiki/Body_Parts should be changed back to this http://wiki.sa-mp.com/wroot/index.php?title=Body_Parts&oldid=37857 too.

**Comment by ziggi** [comment]
> So this http://wiki.sa-mp.com/wiki/Body_Parts should be changed back to this http://wiki.sa-mp.com/wroot/index.php?title=Body_Parts&oldid=37857 too.

Why? We have [Bone_IDs page](http://wiki.sa-mp.com/wiki/Bone_IDs), where each part of body is not written like define constant.

**Comment by rt-2** [comment]
Yes you are right, they are not defined by default.

**Comment by ziggi** [comment]
Done (wiki updated too). Any suggestions? Or I can close the issue?

**Comment by IstuntmanI** [comment]
I tested with that filterscript again and it looks like IDs 0, 1 and 2 aren't used anywhere. I don't understand why those IDs are starting from 3.

You can close the issue.

**Comment by ziggi** [comment]
I think that San Andreas dev's had plans about 0, 1, 2 id's but they declined this for some reasons.
