### ISSUE TITLE
Locked driver door animation, exact time.

### ISSUE THREAD

**Issue by rt-2** [Open-GTO/sa-mp-fixes#69]
Hi,
I wanted to know about this line @ziggi : https://github.com/Open-GTO/sa-mp-fixes/blob/master/fixes.inc#L5808.
I see you put 4 seconds, which is a pretty round value. It seems to work fine, but sometime, rarely but sometime, my players get kicked for teleporting into a vehicle by my anticheat when trying to enter one normally, it happened to me too. I know it comes from this script, and I was wondering why did you choose that value, maybe I can make my own test and put something even more exact.
That is happening very rarely but its noticeable.
Thank you,
rt-2

**Comment by ziggi** [comment]
I think that this is almost maximum time for entering to vehicle from the point. And I completely don't understand how anticheat kicks players for teleporting into a vehicle, because this script doesn't teleports players into vehicles at all.

This can be improved with intercepting players keys for understanding when players stops entering to vehicles. And then call `_FIXES_StopPlayerEnterVehicle`.

UPD: Also I forgot to add this into the `OnPlayerDisconnect` callback:
```Pawn
if (FIXES_gsPlayerBools[playerid] & e_FIXES_BOOLS_VEH_ENTER_ANIM)
{
	_FIXES_StopPlayerEnterVehicle(playerid);
}
```

**Comment by rt-2** [comment]
That might be why? The vehicle is still 'locked' for other scripts, but this script haven't locked the vehicle, so a player can enter the vehicle and when the anticheat asks if it's locked the script says yes.
I remember last time that I got kicked I think I just relogged, not sure but this could cause it maybe.
I think you should add it tot he file!
rt-2

**Comment by ziggi** [comment]
@rt-2 this can be closed now?

**Comment by rt-2** [comment]
I think, I'll reopen if I see it happen again. I'm sorry haven't been active recently, bad memory but I really think this is fixed...
Thank you,
rt-2
