### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by MichaelAceAnderson** [Open-GTO/sa-mp-fixes#88]
Hi, I've put #include fixes.inc after a_samp but the compiler crashes without any error
Just a msgbox "Pawn Compiler has stopped working"

**Comment by 0x1E4** [comment]
Yeah me too..

**Comment by NexiusTailer** [comment]
Try to compile with [this compiler](https://github.com/pawn-lang/compiler/releases/tag/v3.10.8) in order to detect the reason of crashes (more like that it will show some errors instead of crashing) and you'll be able to find specific code which cause the problem. However, it can also compile without errors or crash the same way... so
