### ISSUE TITLE
Error 001 | 010 | 017

### ISSUE THREAD

**Issue by XEGARE** [Open-GTO/sa-mp-fixes#94]
Hello! Errors at compilation. Sorry, that's Russian.

> C:\server\pawno\include\fixes.inc(3106) : ошибка 001: ожидался токен "-identifier-", но найден "enum"
C:\server\pawno\include\fixes.inc(3109) : ошибка 010: неверная функция или объявление
C:\server\pawno\include\fixes.inc(3113) : ошибка 010: неверная функция или объявление
C:\server\pawno\include\fixes.inc(3116) : ошибка 010: неверная функция или объявление
C:\server\pawno\include\fixes.inc(3128) : ошибка 001: ожидался токен "-identifier-", но найден "enum"
C:\server\pawno\include\fixes.inc(3131) : ошибка 010: неверная функция или объявление
C:\server\pawno\include\fixes.inc(3133) : ошибка 010: неверная функция или объявление
C:\server\pawno\include\fixes.inc(3162) : ошибка 001: ожидался токен "-identifier-", но найден "enum"
C:\server\pawno\include\fixes.inc(3165) : ошибка 010: неверная функция или объявление
C:\server\pawno\include\fixes.inc(3419) : ошибка 017: необъявленный символ "E_FIXES_WORLDBOUND_DATA"
C:\server\pawno\include\fixes.inc(3481) : ошибка 017: необъявленный символ "e_FIXES_SETTINGS_SECOND_USE"
C:\server\pawno\include\fixes.inc(5689) : ошибка 017: необъявленный символ "e_FIXES_SETTINGS_SECOND_USE"
C:\server\pawno\include\fixes.inc(5788) : ошибка 017: необъявленный символ "e_FIXES_SETTINGS_SECOND_USE"
C:\server\pawno\include\fixes.inc(5806) : ошибка 017: необъявленный символ "e_FIXES_SETTINGS_SECOND_USE"
C:\server\pawno\include\fixes.inc(5806) : предупреждение 213: несовпадение типов
C:\server\pawno\include\fixes.inc(5817) : ошибка 017: необъявленный символ "e_FIXES_SETTINGS_INTERIOR"
C:\server\pawno\include\fixes.inc(5817) : предупреждение 213: несовпадение типов
C:\server\pawno\include\fixes.inc(6191) : ошибка 017: необъявленный символ "e_FIXES_BOOLS_ON_PLAYER_CONNECT"
C:\server\pawno\include\fixes.inc(6191) : предупреждение 213: несовпадение типов
C:\server\pawno\include\fixes.inc(6237) : ошибка 017: необъявленный символ "E_FIXES_WORLDBOUND_DATA_UX"
C:\server\pawno\include\fixes.inc(6237) -- (6238) : предупреждение 213: несовпадение типов
C:\server\pawno\include\fixes.inc(6365) : ошибка 017: необъявленный символ "e_FIXES_BOOLS_ON_PLAYER_CONNECT"
C:\server\pawno\include\fixes.inc(6365) : предупреждение 213: несовпадение типов
C:\server\pawno\include\fixes.inc(6474) : ошибка 017: необъявленный символ "e_FIXES_BOOLS_VEH_ENTER"
C:\server\pawno\include\fixes.inc(6513) : ошибка 017: необъявленный символ "e_FIXES_BOOLS_DIED_TO_SPAWN"
C:\server\pawno\include\fixes.inc(6513) : предупреждение 213: несовпадение типов
C:\server\pawno\include\fixes.inc(6675) : ошибка 017: необъявленный символ "e_FIXES_BOOLS_DIED_TO_SPAWN"
C:\server\pawno\include\fixes.inc(6675) : предупреждение 213: несовпадение типов
C:\server\pawno\include\fixes.inc(6750) : ошибка 017: необъявленный символ "e_FIXES_BOOLS_DIED_TO_SPAWN"
C:\server\pawno\include\fixes.inc(6752) : ошибка 017: необъявленный символ "e_FIXES_BOOLS_DIED_TO_SPAWN"
C:\server\pawno\include\fixes.inc(6752) : предупреждение 213: несовпадение типов
C:\server\pawno\include\fixes.inc(7085) : ошибка 017: необъявленный символ "e_FIXES_BOOLS_BLOCK"
C:\server\pawno\include\fixes.inc(7098) : ошибка 017: необъявленный символ "e_FIXES_BOOLS_VEH_ENTER"
C:\server\pawno\include\fixes.inc(7108) : ошибка 017: необъявленный символ "e_FIXES_BOOLS_VEH_ENTER_ANIM"

Компиляция остановлена.

Pawn compiler 3.2.3664	 	 	Copyright (c) 1997-2017, ITB CompuPhase

Ошибок:26

I use PawnVSCode

**Comment by Y-Less** [comment]
That looks like a custom compiler if the errors are in Russian.  This is tested on the default compiler, and the latest version of Zeex's (community) compiler.  Any others, just update to the latest version here:

https://github.com/pawn-lang/compiler

Your version lists `3.2.3664`, but the errors come from the use of `static enum`, which is hidden behind a compiler version check.  So it sounds like you have a custom compiler that is mis-reporting its version but doesn't support the latest features.

**Comment by Y-Less** [comment]
The root cause is here:

https://github.com/Open-GTO/sa-mp-fixes/blob/8e45243c2633fd68432287ada84a334101167c46/fixes.inc#L1827-L1829

As you can see, it checks:

```
#if ((__Pawn & 0x0F) >= 0x0A) || ((__Pawn & 0xF0) >= 0xA0)
```

Which means you have a compiler that has adjusted the `__Pawn` constant - what compiler is that, and what are the values of `__Pawn` and `__PawnBuild`?

**Comment by Y-Less** [comment]
I've pushed a new version that checks even more versions, but I still recommend you update to the latest version of the compiler.

**Comment by ziggi** [comment]
Discussion about Russian compiler (on Russian): http://pro-pawn.ru/showthread.php?3586
Sources: https://github.com/vlakam/ruspawncc

**Comment by Y-Less** [comment]
Спасибо

**Comment by Daniel-Cortez** [comment]
Yeah, that thing was entirely experimental. Now I'm not even sure if I should've taken part in its development, since now I have to discourage people from using it because it misleads people from using the latest version of a much better "community" compiler -_-

Also I really doubt about misreported version. As far as I can remember, @vlakam forked the code from the Zeex's repo back in 2013, before it became labeled as "3.10". We only translated warnings and errors, added text conversion through the Windows-specific `CharToOem` function, applied a staging buffer reallocation bug fix and added recursion detection.

Though I find suspicious the following code:
```Pawn
#if ((__Pawn & 0x0F) >= 0x0A) || ((__Pawn & 0xF0) >= 0xA0)
```
What does `(__Pawn & 0xF0) >= 0xA0` mean here? Is this a typo or are there some "secret plans" for increasing the compiler's major version number from 3 to 10 (0xA) in the future?
